on:
  push:
    paths:
    - '**.md'
name: Markdown files linkcheck
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: ocular-d/md-linkcheck-action@1.0.1
    - name: md-linkcheck
      uses: ./